#Profile: dev
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ait_springboot_template_example
    username: postgres
    password: postgress

restclient:
  url:
    reqres: https://reqres.in/api
