#Profile: dev
spring:
  datasource:
    url: jdbc:postgresql://ait-psql.akarinti.tech/ait_springboot_template_example
    username: postgres
    password: I7bcfi5aOC

restclient:
  url:
    reqres: https://reqres.in/api
